name: First Workflow

on:
    workflow_dispatch:

jobs:
    learn-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              id: print-hello-world
              run: |
                  echo "hello world 1";
                  echo "hello world 2";

            - name: Print Good Bye
              run: | 
                  echo "Good Bye 1";
                  echo "Good Bye 2";

    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hi
              id: print-hi
              env:
                  GITHUB_TOKEN: AABBBCCCC
              run: |
                  echo "Hi world 1";
                  echo "hi world 2";
                  echo "github token in same step: $GITHUB_TOKEN";

            - name: Print Bye
              run: |
                  echo "Bye 1";
                  echo "Bye 2";
                  echo "github token in other step but same job(can't access): $GITHUB_TOKEN";
